In [1]:
print('hello')

hello


In [5]:
import numpy as np
import matplotlib.pyplot

In [6]:
v2= np.array([2,5,4,7])
v3= np.array([[2],[5],[4],[7]])
v4 = v2.T
print(v2,v3,v4)

[2 5 4 7] [[2]
 [5]
 [4]
 [7]] [2 5 4 7]


In [10]:
v2= np.array([2,5,4,7])
v3 =np.array([4,1,0,2])

v1= 4*v2 - 2*v3
v1

array([ 0, 18, 16, 24])

In [17]:
v2= np.array([2,5,4,7])
v3 =np.array([4,1,0,2])

dp = np.dot(v2,v3)
op = np.outer(v2,v3)
print(dp)
print(op)
 
v4= v2 * v3

27


array([[ 8,  2,  0,  4],
       [20,  5,  0, 10],
       [16,  4,  0,  8],
       [28,  7,  0, 14]])

In [15]:
l1=1
l2=2
l3=-3

v1= np.array([4,5,1])
v2= np.array([-4,0,-4])
v3= np.array([1,3,2])

l1*v1 +l2*v2 +l3*v3

array([ -7,  -4, -13])

In [19]:
v2= np.array([2,5,4,7])

vmag = np.linalg.norm(v2)

vunit= v2 / vmag
vunit

array([0.20628425, 0.51571062, 0.4125685 , 0.72199487])